version: "3.9"

services:
  fuwal:
    image: ghcr.io/fullon-labs/floncore/funod:0.5.0
    container_name: fuwal
    working_dir: /opt/flon
    entrypoint: ["./bin/run-wallet.sh", "."]
    volumes:
      - /Users/joss/.fuwal/:/opt/flon
      - /Users/joss/.fuwal/bin/.bashrc:/root/.bashrc
      - /Users/joss/.fuwal/bin-script:/root/bin
    dns:
      - 114.114.114.114
      - 8.8.8.8
networks:
  default:
    name: flon
    external: true
