version: '3.8'

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}  # 默认数据库
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    stop_signal: SIGTERM
    stop_grace_period: 300s

  scan-svc:
    container_name: ${SCAN_CONTAINER_NAME}
    image: ${HISTORY_TOOLS_IMAGE}
    working_dir: ${SCAN_WORK_PATH}
    entrypoint: ["./bin/start.sh", "${SCAN_WORK_PATH}", ""]
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=${PG_HOST}
      - PGDATABASE=${POSTGRES_DB:-postgres}
    volumes:
      - ${SCAN_WORK_PATH}:${SCAN_WORK_PATH}
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    stop_signal: SIGTERM
    stop_grace_period: 300s

networks:
  default:
    name: flon
    external: true