version: '3.8'

services:
  postgres:
    container_name: "postgres_scan_testnet"
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scan_testnet
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - "/mnt/data1/postgres_scan_testnet/pgdata:/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    stop_signal: SIGTERM
    stop_grace_period: 5s

networks:
  default:
    name: flon
    external: true