image:
  repository: ghcr.io/fullon-labs/floncore/funod
  tag: 0.6.4
  pullPolicy: IfNotPresent

replicaCount: 1  # 优化成本，单节点运行

service:
  type: NodePort
  httpPort: 8888
  p2pPort: 9876
  annotations: {}

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: t.fufi.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: false

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "800m"
    memory: "2Gi"

nodeSelector: {}

affinity: {}

tolerations: []

chain:
  chainStateDbSizeMB: 65536
  reversibleDbSizeMB: 4096
  readMode: speculative
  netThreads: 4
  chainThreads: 4
  httpThreads: 6
  syncFetchSpan: 200
  maxTransactionTime: 1000
  abiSerializerMaxTimeMs: 2000
  p2pMaxNodesPerHost: 100
  accessControlAllowOrigin: "*"
  httpValidateHost: false

# peers 列表（p2p-peer-address）
peers:
  - hk-t1.vm.nestar.vip:19806
#  - peer1.flon.example.com:9876
#  - peer2.flon.example.com:9876

# genesis.json 内容：默认仅占位，主网通常不需要这里（已有链数据/快照）。
genesis:
  enabled: false
  content: |
    {
      "initial_timestamp": "2025-01-01T08:00:00.000",
      "initial_key": "FU6JCHZ1boJBxjAwmUykCLFe9ipsR44GNTL2w4zgudwjVtHvbgTT",
      "initial_configuration": {
        "max_block_net_usage": 1048576,
        "max_transaction_net_usage": 524288,
        "base_per_transaction_net_usage": 12,
        "net_usage_leeway": 500,
        "context_free_discount_net_usage_num": 20,
        "context_free_discount_net_usage_den": 100,
        "max_block_cpu_usage": 200000,
        "max_transaction_cpu_usage": 150000,
        "min_transaction_cpu_usage": 100,
        "max_transaction_lifetime": 3600,
        "max_inline_action_size": 524288,
        "max_inline_action_depth": 4,
        "max_authority_depth": 6,
        "max_total_ram_usage": 68719476736,
        "gas_per_cpu_ms": 10000,
        "gas_per_net_kb": 50000,
        "gas_per_ram_kb": 50000
      }
    }

# 从快照启动（可选）
snapshot:
  enabled: true
  # 支持 .bin 或 .zst
  url: "https://flon-test.oss-cn-hongkong.aliyuncs.com/snapshots/snapshot-0112e5a55036637fa05a3ccf3dde370816b216092d87b9b2626f9f0cc0e77e17.bin"

producer:
  enabled: false
  name: yourbpname
  signatureProvider: "FUxxxx=KEOSD:PW5Kxxxxx"

# 探针
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 20
  timeoutSeconds: 5
  # 与 head_block_time 的最大滞后（秒）
  maxBehindSeconds: 180

# 是否启用 ServiceMonitor（用于 Prometheus Operator）
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 5s
  labels: {}

podAnnotations: {}

extraEnv: []
#  - name: HTTP_PROXY
#    value: http://proxy:8080

extraVolumes: []
extraVolumeMounts: []

priorityClassName: ""