image:
  repository: ghcr.io/fullon-labs/floncore/funod
  tag: 0.6.4
  pullPolicy: IfNotPresent

replicaCount: 1  # 单节点；如需水平扩，建议配多数据副本并注意 P2P 配置

service:
  type: ClusterIP
  httpPort: 8888
  p2pPort: 9876
  annotations: {}

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: flon-rpc.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClassName: fast-ssd
  accessModes: ["ReadWriteOnce"]
  size: 300Gi

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "8"
    memory: "16Gi"

nodeSelector: {}

affinity: {}

tolerations: []

chain:
  chainStateDbSizeMB: 65536
  reversibleDbSizeMB: 4096
  readMode: speculative
  netThreads: 4
  chainThreads: 4
  httpThreads: 6
  syncFetchSpan: 200
  maxTransactionTime: 1000
  abiSerializerMaxTimeMs: 2000
  p2pMaxNodesPerHost: 100
  accessControlAllowOrigin: "*"
  httpValidateHost: false

# peers 列表（p2p-peer-address）
peers: []
#  - peer1.flon.example.com:9876
#  - peer2.flon.example.com:9876

# genesis.json 内容：默认仅占位，主网通常不需要这里（已有链数据/快照）。
genesis:
  enabled: true
  content: |
    {
      "initial_timestamp": "2018-06-08T08:08:08.888",
      "initial_key": "EOS6MRy..ReplaceThis..",
      "initial_configuration": {
        "max_block_net_usage": 1048576,
        "target_block_net_usage_pct": 1000,
        "max_transaction_net_usage": 524288,
        "base_per_transaction_net_usage": 12,
        "net_usage_leeway": 500,
        "context_free_discount_net_usage_num": 20,
        "context_free_discount_net_usage_den": 100,
        "max_block_cpu_usage": 200000,
        "target_block_cpu_usage_pct": 1000,
        "max_transaction_cpu_usage": 150000,
        "min_transaction_cpu_usage": 100,
        "max_transaction_lifetime": 3600,
        "deferred_trx_expiration_window": 600,
        "max_transaction_delay": 3888000,
        "max_inline_action_size": 4096,
        "max_inline_action_depth": 4,
        "max_authority_depth": 6
      }
    }

# 从快照启动（可选）
snapshot:
  enabled: false
  # 支持 .bin 或 .zst
  url: "https://your-bucket/snapshots/flon-snap-<height>.bin.zst"

producer:
  enabled: false
  name: yourbpname
  signatureProvider: "EOSxxxx=KEOSD:PW5Kxxxxx"

# 探针
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 20
  timeoutSeconds: 5
  # 与 head_block_time 的最大滞后（秒）
  maxBehindSeconds: 180

# 是否启用 ServiceMonitor（用于 Prometheus Operator）
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 5s
  labels: {}

podAnnotations: {}

extraEnv: []
#  - name: HTTP_PROXY
#    value: http://proxy:8080

extraVolumes: []
extraVolumeMounts: []

priorityClassName: ""