version: '3.8'

services:

   scan-svc:
    container_name: ${SCAN_CONTAINER_NAME}
    image: ${HISTORY_TOOLS_IMAGE}
    working_dir: ${SCAN_WORK_PATH}
    entrypoint: ["./bin/start.sh", "${SCAN_WORK_PATH}", ""]
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=${PG_HOST}
      - PGPORT=${PG_PORT}
      - PGDATABASE=${POSTGRES_DB:-postgres}
    volumes:
      - ${SCAN_WORK_PATH}:${SCAN_WORK_PATH}
    restart: on-failure
    stop_signal: SIGTERM
    stop_grace_period: 5s
    dns:
      - 8.8.8.8
      - 223.5.5.5

networks:
  default:
    name: flon
    external: true