version: "3.9"

services:
  node:
    image: ${NODE_IMG_HEADER}floncore/funod:${FULLON_VERSION}
    container_name: ${node_name}
    working_dir: ${NODE_WORK_PATH}
    entrypoint: ["./bin/start.sh", "${NODE_WORK_PATH}", ""]
    restart: always
    privileged: true
    ports: 
      - "${RPC_PORT}:8888"
      - "${P2P_PORT}:9876"
      - "${HIST_WS_PORT}:9555"
    volumes:
      - ${NODE_WORK_PATH}:${NODE_WORK_PATH}
    dns:
      - 114.114.114.114
      - 8.8.8.8
      
networks:
  default:
    name: flon
    external: true