{{- if .Values.snapshot.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flon-node.fullname" . }}-snapshot
  labels:
    {{- include "flon-node.labels" . | nindent 4 }}
stringData:
  snapshot_url: {{ .Values.snapshot.url | quote }}
{{- end }}