{{- if .Values.producer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flon-node.fullname" . }}-producer
  labels:
    {{- include "flon-node.labels" . | nindent 4 }}
stringData:
  signature_provider: {{ .Values.producer.signatureProvider | quote }}
{{- end }}